=== CoolProp/CoolProp/dev/mixtures/mixture_departure_functions_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Set of departure functions for CoolProp",
    "type": "array",
    "items": {
        "title": "Departure function",
        "type": "object",
        "properties": {
            "BibTeX": {
                "description": "The BibTeX key for the reference",
                "type": "string"
            },
            "Name": {
                "description": "Name of the binary pair - must be unique",
                "type": "string"
            },
            "type": {
                "description": "Type of the binary pair reducing function",
                "type": "string",
                "enum": ["GERG-2008", "Exponential", "Gaussian+Exponential"]
            },
            "n": {
                "type": "array",
                "items": {
                    "type": "number"
                },
                "minItems": 0
            },
            "d": {
                "type": "array",
                "items": {
                    "type": "number"
                },
                "minItems": 0
            },
            "t": {
                "type": "array",
                "items": {
                    "type": "number"
                },
                "minItems": 0
            },
            "l": {
                "type": "array",
                "items": {
                    "type": "number"
                },
                "minItems": 0
            },
            "eta": {
                "type": "array",
                "items": {
                    "type": "number"
                },
                "minItems": 0
            },
            "epsilon": {
                "type": "array",
                "items": {
                    "type": "number"
                },
                "minItems": 0
            },
            "beta": {
                "type": "array",
                "items": {
                    "type": "number"
                },
                "minItems": 0
            },
            "gamma": {
                "type": "array",
                "items": {
                    "type": "number"
                },
                "minItems": 0
            },
            "aliases": {
                "type": "array",
                "items": {
                    "type": "string"
                },
                "minItems": 0,
                "uniqueItems": true
            }
        },
        "required": ["n", "d", "t", "type", "Name", "BibTeX", "aliases"]
    }
}

=== CoolProp/CoolProp/dev/mixtures/mixture_departure_functions.json
[
{
"Name" : "R32-R125",
"BibTeX" : "Lemmon-JPCRD-2004",
"aliases" : ["KWR"],
"type" : "Exponential",
"n" : [-0.0072955, 0.078035, 0.61007, 0.64246, 0.014965, -0.34049, 0.085658, -0.064429],
"t" : [4.5, 0.57, 1.9, 1.2, 0.5, 2.6, 11.4, 4.5],
"d" : [2, 5, 1, 3, 9, 2, 3, 6],
"l" : [1, 1, 2, 2, 2, 3, 3, 3]
},
{
"Name" : "R32-R134a",
"BibTeX" : "Lemmon-JPCRD-2004",
"aliases" : ["KWS"],
"type" : "Exponential",
"n" : [0.22909, 0.094074, 0.00039876, 0.021113],
"t" : [1.9, 0.25, 0.07, 2.0],
"d" : [1, 3, 8, 1],
"l" : [1, 1, 1, 2]
},
{
"Name" : "GeneralizedHFC",
"BibTeX" : "Lemmon-JPCRD-2004",
"aliases" : ["KWT","LJ6"],
"type" : "Exponential",
"n" : [-0.013073, 0.018259,0.0000081299,0.0078496],
"t" : [7.4, 0.35, 10.0, 5.3],
"d" : [1, 3, 11, 2],
"l" : [1, 1, 2, 3]
},
{
"Name" : "GeneralizedAirComponents",
"BibTeX" : "Lemmon-JPCRD-2000",
"aliases" : [],
"type" : "Exponential",
"n" : [-0.00195245, 0.00871334],
"t" : [-1.4, 1.5],
"d" : [2, 2],
"l" : [0, 0]
},
{
"Name" : "Ethanol-Water",
"aliases" : ["KW8"],
"BibTeX" : "From REFPROP 9.1 with permission",
"type" : "Exponential",
"n" : [1.09765e+00, 1.94679e+00, -2.16809e+00, -1.37077e-01, 4.86690e-02, 1.04024e+00],
"t" : [0.26, 7.3, 5.3, 2.3, 0.7, 3.3],
"d" : [2, 3, 5, 5, 7, 6],
"l" : [1, 2, 2, 1, 1, 2]
},
{
"Name" : "Methane-Nitrogen",
"aliases" : ["KW3"],
"type" : "GERG-2008",
"BibTeX" : "Kunz-JCED-2012",
"Npower" : 2,
"d" : [1, 4, 1, 2, 2, 2, 2, 2, 3],
"t" : [0.0, 1.85, 7.85, 5.4, 0.0, 0.75, 2.8, 4.45, 4.25],
"n" : [-0.0098038985517335, 0.00042487270143005, -0.034800214576142, -0.13333813013896, -0.011993694974627, 0.069243379775168, -0.31022508148249, 0.24495491753226, 0.22369816716981],
"eta" : [0.0, 0.0, 1.0, 1.0, 0.25, 0.0, 0.0, 0.0, 0.0],
"epsilon" : [0.0, 0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
"beta": [0.0, 0.0, 1.0, 1.0, 2.5, 3.0, 3.0, 3.0, 3.0],
"gamma": [0.0, 0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
},
{
"Name" : "Methane-CarbonDioxide",
"aliases" : ["KW4"],
"type" : "GERG-2008",
"BibTeX" : "Kunz-JCED-2012",
"Npower" : 3,
"d" : [1, 2, 3, 1, 2, 3],
"t" : [2.6, 1.95, 0.0, 3.95, 7.95, 8.0],
"n" : [-0.10859387354942, 0.080228576727389, -0.0093303985115717, 0.040989274005848, -0.24338019772494, 0.23855347281124],
"eta" : [0.0, 0.0, 0.0, 1.0, 0.5, 0.0],
"epsilon" : [0.0, 0.0, 0.0, 0.5, 0.5, 0.5],
"beta": [0.0, 0.0, 0.0, 1.0, 2.0, 3.0],
"gamma": [0.0, 0.0, 0.0, 0.5, 0.5, 0.5]
},
{
"Name" : "Methane-Ethane",
"aliases" : ["KW1"],
"type" : "GERG-2008",
"BibTeX" : "Kunz-JCED-2012",
"Npower" : 2,
"d" : [3, 4, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3],
"t" : [0.65, 1.55, 3.1, 5.9, 7.05, 3.35, 1.2, 5.8, 2.7, 0.45, 0.55, 1.95],
"n" : [-0.00080926050298746, -0.00075381925080059, -0.041618768891219, -0.23452173681569, 0.14003840584586, 0.063281744807738, -0.034660425848809, -0.23918747334251, 0.0019855255066891, 6.1777746171555, -6.9575358271105, 1.0630185306388],
"eta" : [0.0, 0.0, 1.0, 1.0, 1.0, 0.875, 0.75, 0.5, 0.0, 0.0, 0.0, 0.0],
"epsilon" : [0.0, 0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
"beta": [0.0, 0.0, 1.0, 1.0, 1.0, 1.25, 1.5, 2.0, 3.0, 3.0, 3.0, 3.0],
"gamma": [0.0, 0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
},
{
"Name" : "Methane-Propane",
"aliases" : ["KW2"],
"type" : "GERG-2008",
"BibTeX" : "Kunz-JCED-2012",
"Npower" : 5,
"d" : [3, 3, 4, 4, 4, 1, 1, 1, 2],
"t" : [1.85, 3.95, 0.0, 1.85, 3.85, 5.25, 3.85, 0.2, 6.5],
"n" : [0.013746429958576, -0.0074425012129552, -0.0045516600213685, -0.0054546603350237, 0.0023682016824471, 0.18007763721438, -0.44773942932486, 0.0193273748882, -0.30632197804624],
"eta" : [0.0, 0.0, 0.0, 0.0, 0.0, 0.25, 0.25, 0.0, 0.0],
"epsilon" : [0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5, 0.5, 0.5],
"beta": [0.0, 0.0, 0.0, 0.0, 0.0, 0.75, 1.0, 2.0, 3.0],
"gamma": [0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5, 0.5, 0.5]
},
{
"Name": "Nitrogen-CarbonDioxide",
"aliases" : ["KW5"],
"type" : "GERG-2008",
"BibTeX" : "Kunz-JCED-2012",
"Npower" : 2,
"d" : [2, 3, 1, 1, 1, 2],
"t" : [1.85, 1.4, 3.2, 2.5, 8.0, 3.75],
"n" : [0.28661625028399, -0.10919833861247, -1.137403208227, 0.76580544237358, 0.0042638000926819, 0.17673538204534],
"eta" : [0.0, 0.0, 0.25, 0.25, 0.0, 0.0],
"epsilon" : [0.0, 0.0, 0.5, 0.5, 0.5, 0.5],
"beta": [0.0, 0.0, 0.75, 1.0, 2.0, 3.0],
"gamma": [0.0, 0.0, 0.5, 0.5, 0.5, 0.5]
},
{
"Name": "Nitrogen-Ethane",
"aliases" : ["KW6"],
"type" : "GERG-2008",
"BibTeX" : "Kunz-JCED-2012",
"Npower" : 3,
"d" : [2, 2, 3, 1, 2, 2],
"t" : [0.0, 0.05, 0.0, 3.65, 4.9, 4.45],
"n" : [-0.47376518126608, 0.48961193461001, -0.0057011062090535, -0.1996682004132, -0.69411103101723, 0.69226192739021],
"eta" : [0.0, 0.0, 0.0, 1.0, 1.0, 0.875],
"epsilon" : [0.0, 0.0, 0.0, 0.5, 0.5, 0.5],
"beta": [0.0, 0.0, 0.0, 1.0, 1.0, 1.25],
"gamma": [0.0, 0.0, 0.0, 0.5, 0.5, 0.5]
},
{
"Name": "Methane-Hydrogen",
"aliases" : ["KW7"],
"type" : "GERG-2008",
"BibTeX" : "Kunz-JCED-2012",
"Npower" : 4,
"d" : [1, 3, 3, 4],
"t" : [2.0, -1.0, 1.75, 1.4],
"n" : [-0.25157134971934, -0.0062203841111983, 0.088850315184396, -0.035592212573239],
"eta" : [0.0, 0.0, 0.0, 0.0],
"epsilon" : [0.0, 0.0, 0.0, 0.0],
"beta": [0.0, 0.0, 0.0, 0.0],
"gamma": [0.0, 0.0, 0.0, 0.0]
},
{
"Name" : "GeneralizedAlkane",
"aliases" : ["KW0"],
"type" : "GERG-2008",
"BibTeX" : "Kunz-JCED-2012",
"Npower" : 10,
"d" : [1, 1, 1, 2, 2, 3, 3, 4, 4, 4],
"t" : [1.0, 1.55, 1.7, 0.25, 1.35, 0.0, 1.25, 0.0, 0.7, 5.4],
"n" : [2.5574776844118, -7.9846357136353, 4.7859131465806, -0.73265392369587, 1.3805471345312, 0.28349603476365, -0.49087385940425, -0.10291888921447, 0.11836314681968, 5.5527385721943e-05],
"eta" : [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
"epsilon" : [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
"beta": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
"gamma": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
},
{
"Name" : "CarbonDioxide-Water",
"aliases" : [],
"type" : "Exponential",
"BibTeX" : "Gernert-Thesis-2013",
"Npower" : 8,
"d" : [1, 1, 3, 0, 2, 3, 1, 5],
"t" : [0.880, 2.932, 2.433, 1.330, 4.416, 5.514, 5.203, 1.000],
"n" : [3.9440467e-1, -1.7634732, 1.4620755e-1, 8.7522320e-3, 2.0349398, -9.0350250e-2, -2.1638854e-1, 3.9612170e-2],
"l" : [0, 0, 0, 1, 1, 1, 2, 2]
},
{
"Name" : "GeneralizedAirWater",
"aliases" : [],
"type" : "Exponential",
"BibTeX" : "Gernert-Thesis-2013",
"Npower" : 5,
"d" : [1, 1, 1, 2, 4],
"t" : [0.547, 0.055, 1.925, 0.552, 1.000],
"n" : [4.0142079, -1.1573939, -7.2102425, -5.3251223, -2.2155867],
"l" : [0, 1, 1, 1, 1]
},
{
"Name": "Argon-CarbonDioxide",
"aliases" : [],
"type" : "GERG-2008",
"BibTeX" : "Gernert-Thesis-2013",
"Npower" : 2,
"d" : [2, 3, 1, 1, 1, 2],
"t" : [2.194, 1.743, 2.470, 1.977, 1.207, 0.796],
"n" : [2.0483577e-1, -1.1465124e-1 , -2.3151700, 2.3523617, -6.6835959e-1, -5.3016558e-2],
"eta" : [0.0, 0.0, 0.25, 0.25, 0.0, 0.0],
"epsilon" : [0.0, 0.0, 0.5, 0.5, 0.5, 0.5],
"beta": [0.0, 0.0, 0.75, 1.0, 1.05, 3.0],
"gamma": [0.0, 0.0, 0.5, 0.5, 0.5, 0.5]
},
{
"Name" : "R1234yf-R134a",
"BibTeX" : "Bell-JPCRD-2022",
"aliases" : [],
"type" : "Exponential",
"n" : [0.051900, -0.011472],
"t" : [2.477314, 0.070541],
"d" : [1, 2],
"l" : [1, 2]
},
{
"Name" : "R1234yf-R1234ze(E)",
"BibTeX" : "Bell-JPCRD-2022",
"aliases" : [],
"type" : "Exponential",
"n" : [0.072640, -0.024746],
"t" : [0.012645, 3.992829],
"d" : [1, 2],
"l" : [1, 2]
},
{
"Name" : "R134a-R1234ze(E)",
"BibTeX" : "Bell-JPCRD-2022",
"aliases" : [],
"type" : "Exponential",
"n" : [0.068889, -0.004831],
"t" : [3.184446, 2.034344],
"d" : [1, 2],
"l" : [1, 2]
},
{
"Name" : "R32-R1234yf",
"BibTeX" : "Bell-JPCRD-2023",
"aliases" : [],
"type" : "Exponential",
"n" : [0.449487, -0.099708, 0.098897],
"t" : [2.538296, 3.208604, 0.456509],
"d" : [1, 2, 3],
"l" : [1, 1, 1]
},
{
"Name" : "R32-R1234ze(E)",
"BibTeX" : "Bell-JPCRD-2023",
"aliases" : [],
"type" : "Exponential",
"n" : [0.295192, -0.737904, 0.542962, -0.201951],
"t" : [0.500457, 3.104735, 3.201720, 2.567118],
"d" : [1, 2, 3, 4],
"l" : [1, 1, 1, 1]
},
{
"Name" : "R1234yf-R152a",
"BibTeX" : "Bell-JPCRD-2023",
"aliases" : [],
"type" : "Exponential",
"n" : [0.009165, 0.014392, -0.014246],
"t" : [3.221227, 1.007082, 3.790953],
"d" : [1, 2, 3],
"l" : [1, 1, 1]
},
{
"Name" : "R125-R1234yf",
"BibTeX" : "Bell-JPCRD-2023",
"aliases" : [],
"type" : "Exponential",
"n" : [-0.032013],
"t" : [0.00803],
"d" : [1],
"l" : [1]
},
{
"Name" : "R1234ze(E)-R227ea",
"BibTeX" : "Bell-JPCRD-2023",
"aliases" : [],
"type" : "Exponential",
"n" : [-0.057178, 0.031318, -0.027496],
"t" : [1.290298, 0.038796, 2.640532],
"d" : [1, 2, 3],
"l" : [1, 1, 1]
},
{
"Name" : "R1336mzz(Z)-R1130(E)",
"BibTeX" : "McLinden-NISTIR-8570",
"aliases" : [],
"type" : "Exponential",
"n" : [-0.277036],
"t" : [2.956973],
"d" : [1],
"l" : [1]
},
{
"Name" : "Helium-Neon",
"BibTeX" : "Tkaczuk-JPCRD-2020",
"aliases" : [],
"type" : "Gaussian+Exponential",
"Npower" : 3,
"n" : [-4.346849, -0.884378, 0.258416, 3.502188, 0.831330, 2.740495, -1.582230, -0.304897],
"t" : [1.195, 1.587, 1.434, 1.341, 1.189, 1.169, 0.944, 1.874],
"d" : [1, 2, 3, 1, 2, 3, 4, 4],
"l" : [0, 0, 0, 0, 0, 0, 0, 0],
"eta" : [0.0, 0.0, 0.0, 0.157, 0.931, 0.882, 0.868, 0.543],
"beta" : [0.0, 0.0, 0.0, 0.173, 1.070, 0.695, 0.862, 0.971],
"gamma" : [0.0, 0.0, 0.0, 1.310, 1.356, 1.596, 1.632, 0.766],
"epsilon" : [0.0, 0.0, 0.0, 1.032, 1.978, 1.966, 1.709, 0.583]
},
{
"Name" : "Helium-Argon",
"BibTeX" : "Tkaczuk-JPCRD-2020",
"aliases" : [],
"type" : "Gaussian+Exponential",
"Npower" : 3,
"n" : [-2.643654, -0.347501, 0.201207, 1.171326, 0.216379, 0.561370, 0.182570, 0.017879],
"t" : [1.030, 0.288, 0.572, 1.425, 1.987, 0.024, 1.434, 0.270],
"d" : [1, 2, 3, 1, 1, 2, 3, 4],
"l" : [0, 0, 0, 0, 0, 0, 0, 0],
"eta" : [0.0, 0.0, 0.0, 0.371, 0.081, 0.375, 0.978, 0.971],
"beta" : [0.0, 0.0, 0.0, 0.320, 1.247, 1.152, 0.245, 1.030],
"gamma" : [0.0, 0.0, 0.0, 1.409, 1.709, 0.705, 1.162, 0.869],
"epsilon" : [0.0, 0.0, 0.0, 0.378, 0.741, 0.322, 1.427, 2.088]
},
{
"Name" : "Neon-Argon",
"BibTeX" : "Tkaczuk-JPCRD-2020",
"aliases" : [],
"type" : "Gaussian+Exponential",
"Npower" : 3,
"n" : [-1.039686, 0.593776, -0.186531, -0.223315, 0.160847, 0.405228, -0.264563, -0.033569],
