=== CoolProp/CoolProp/dev/pcsaft/pcsaft_fluids_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Fluid for PC-SAFT EOS in CoolProp",
  "items": {
    "properties": {
      "name": {
        "description": "Name of the fluid",
        "type": "string"
      },
      "CAS": {
        "description": "CAS registry number of the fluid",
        "type": "string"
      },
      "m": {
        "description": "Number of segments (-)",
        "type": "number",
        "minimum": 0,
        "maximum": 1000
      },
      "sigma": {
        "description": "Segment diameter (1/Angstrom)",
        "type": "number",
        "minimum": -2,
        "maximum": 6
      },
      "sigma_units": {
        "description": "Units of the segment diameter provided",
        "enum": [
          "1/Angstrom"
        ]
      },
      "u": {
        "description": "Dispersion energy divided by Boltzmann constant (K)",
        "type": "number",
        "minimum": 0,
        "maximum": 2000
      },
      "u_units": {
        "description": "Units of the dispersion energy provided",
        "enum": [
          "K"
        ]
      },
      "uAB": {
        "description": "Association energy (K)",
        "type": "number",
        "minimum": 0,
        "maximum": 5000
      },
      "uAB_units": {
        "description": "Units of the association energy provided",
        "enum": [
          "K"
        ]
      },
      "volA": {
        "description": "Association volume",
        "type": "number",
        "minimum": 0,
        "maximum": 1
      },
      "volA_units": {
        "description": "Units of the association volume provided",
        "enum": [
          "1/Angstrom^3"
        ]
      },
      "dipm": {
        "description": "Dipole moment (Debye)",
        "type": "number",
        "minimum": 0,
        "maximum": 13
      },
      "dipm_units": {
        "description": "Units of the dipole moment provided",
        "enum": [
          "Debye"
        ]
      },
      "dipnum": {
        "description": "Number of dipole moments per molecule (-)",
        "type": "number",
        "minimum": 0,
        "maximum": 100
      },
      "charge": {
        "description": "Charge of ion (-)",
        "type": "number",
        "minimum": -10,
        "maximum": 10
      },
      "molemass": {
        "description": "Molar mass (kg/mol)",
        "type": "number",
        "minimum": 0,
        "maximum": 1
      },
      "molemass_units": {
        "description": "Units of the molar mass provided",
        "enum": [
          "kg/mol"
        ]
      },
      "aliases": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "minItems": 0
      },
      "BibTeX": {
        "description": "BibTeX reference to the source from which the PC-SAFT parameters were taken",
        "type": "string"
      }
    },
    "required": [
      "name",
      "CAS",
      "m",
      "sigma",
      "sigma_units",
      "u",
      "u_units",
      "molemass",
      "molemass_units"
    ]
  },
  "type": "array"
}

=== CoolProp/CoolProp/dev/pcsaft/all_pcsaft_fluids.json
[
  {
    "CAS": "74-82-8",
    "aliases": [
      "METHANE"
    ],
    "m": 1.0,
    "sigma": 3.7039,
    "sigma_units": "1/Angstrom",
    "u": 150.03,
    "u_units": "K",
    "molemass": 0.016043,
    "molemass_units": "kg/mol",
    "name": "METHANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "74-84-0",
    "aliases": [
      "ETHANE"
    ],
    "m": 1.6069,
    "sigma": 3.5206,
    "sigma_units": "1/Angstrom",
    "u":  191.42,
    "u_units": "K",
    "molemass": 0.03007,
    "molemass_units": "kg/mol",
    "name": "ETHANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "74-98-6",
    "aliases": [
      "PROPANE"
    ],
    "m": 2.0020,
    "sigma": 3.6184,
    "sigma_units": "1/Angstrom",
    "u": 208.11,
    "u_units": "K",
    "molemass": 0.044096,
    "molemass_units": "kg/mol",
    "name": "PROPANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "106-97-8",
    "aliases": [
      "BUTANE",
      "N-BUTANE"
    ],
    "m": 2.3316,
    "sigma": 3.7086,
    "sigma_units": "1/Angstrom",
    "u": 222.88,
    "u_units": "K",
    "molemass": 0.055123,
    "molemass_units": "kg/mol",
    "name": "N-BUTANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "109-66-0",
    "aliases": [
      "PENTANE",
      "N-PENTANE"
    ],
    "m": 2.6896,
    "sigma": 3.7729,
    "sigma_units": "1/Angstrom",
    "u": 231.20,
    "u_units": "K",
    "molemass": 0.072146,
    "molemass_units": "kg/mol",
    "name": "N-PENTANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "110-54-3",
    "aliases": [
      "HEXANE",
      "N-HEXANE"
    ],
    "m": 3.0576,
    "sigma": 3.7983,
    "sigma_units": "1/Angstrom",
    "u": 236.77,
    "u_units": "K",
    "molemass": 0.086177,
    "molemass_units": "kg/mol",
    "name": "N-HEXANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "142-82-5",
    "aliases": [
      "HEPTANE",
      "N-HEPTANE"
    ],
    "m": 3.4831,
    "sigma": 3.8049,
    "sigma_units": "1/Angstrom",
    "u": 238.40,
    "u_units": "K",
    "molemass": 0.100203,
    "molemass_units": "kg/mol",
    "name": "N-HEPTANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "111-65-9",
    "aliases": [
      "OCTANE",
      "N-OCTANE"
    ],
    "m": 3.8176,
    "sigma": 3.8373,
    "sigma_units": "1/Angstrom",
    "u": 242.78,
    "u_units": "K",
    "molemass": 0.114231,
    "molemass_units": "kg/mol",
    "name": "N-OCTANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "111-84-2",
    "aliases": [
      "NONANE",
      "N-NONANE"
    ],
    "m": 4.2079,
    "sigma": 3.8448,
    "sigma_units": "1/Angstrom",
    "u": 244.51,
    "u_units": "K",
    "molemass": 0.12825,
    "molemass_units": "kg/mol",
    "name": "N-NONANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "124-18-5",
    "aliases": [
      "DECANE",
      "N-DECANE"
    ],
    "m": 4.6627,
    "sigma": 3.8384,
    "sigma_units": "1/Angstrom",
    "u": 243.87,
    "u_units": "K",
    "molemass": 0.142285,
    "molemass_units": "kg/mol",
    "name": "N-DECANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "1120-21-4",
    "aliases": [
      "UNDECANE",
      "N-UNDECANE"
    ],
    "m": 4.9082,
    "sigma": 3.8893,
    "sigma_units": "1/Angstrom",
    "u": 248.82,
    "u_units": "K",
    "molemass": 0.156312,
    "molemass_units": "kg/mol",
    "name": "N-UNDECANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "112-40-3",
    "aliases": [
      "DODECANE",
      "N-DODECANE"
    ],
    "m": 5.3060,
    "sigma": 3.8959,
    "sigma_units": "1/Angstrom",
    "u": 249.21,
    "u_units": "K",
    "molemass": 0.170338,
    "molemass_units": "kg/mol",
    "name": "N-DODECANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "629-50-5",
    "aliases": [
      "TRIDECANE",
      "N-TRIDECANE"
    ],
    "m": 5.6877,
    "sigma": 3.9143,
    "sigma_units": "1/Angstrom",
    "u": 249.78,
    "u_units": "K",
    "molemass": 0.184365,
    "molemass_units": "kg/mol",
    "name": "N-TRIDECANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "629-59-4",
    "aliases": [
      "TETRADECANE",
      "N-TETRADECANE"
    ],
    "m": 5.9002,
    "sigma": 3.9396,
    "sigma_units": "1/Angstrom",
    "u": 254.21,
    "u_units": "K",
    "molemass": 0.198392,
    "molemass_units": "kg/mol",
    "name": "N-TETRADECANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "629-62-9",
    "aliases": [
      "PENTADECANE",
      "N-PENTADECANE"
    ],
    "m": 6.2855,
    "sigma": 3.9531,
    "sigma_units": "1/Angstrom",
    "u": 254.14,
    "u_units": "K",
    "molemass": 0.212419,
    "molemass_units": "kg/mol",
    "name": "N-PENTADECANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "544-76-3",
    "aliases": [
      "HEXADECANE",
      "N-HEXADECANE"
    ],
    "m": 6.6485,
    "sigma": 3.9552,
    "sigma_units": "1/Angstrom",
    "u": 254.70,
    "u_units": "K",
    "molemass": 0.226446,
    "molemass_units": "kg/mol",
    "name": "N-HEXADECANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "629-78-7",
    "aliases": [
      "HEPTADECANE",
      "N-HEPTADECANE"
    ],
    "m": 6.9809,
    "sigma": 3.9675,
    "sigma_units": "1/Angstrom",
    "u": 255.65,
    "u_units": "K",
    "molemass": 0.240473,
    "molemass_units": "kg/mol",
    "name": "N-HEPTADECANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "593-45-3",
    "aliases": [
      "OCTADECANE",
      "N-OCTADECANE"
    ],
    "m": 7.3271,
    "sigma": 3.9668,
    "sigma_units": "1/Angstrom",
    "u": 256.20,
    "u_units": "K",
    "molemass": 0.2545,
    "molemass_units": "kg/mol",
    "name": "N-OCTADECANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "629-92-5",
    "aliases": [
      "NONADECANE",
      "N-NONADECANE"
    ],
    "m": 7.7175,
    "sigma": 3.9721,
    "sigma_units": "1/Angstrom",
    "u": 256.00,
    "u_units": "K",
    "molemass": 0.268527,
    "molemass_units": "kg/mol",
    "name": "N-NONADECANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "112-95-8",
    "aliases": [
      "EICOSANE",
      "N-EICOSANE"
    ],
    "m": 7.9849,
    "sigma": 3.9869,
    "sigma_units": "1/Angstrom",
    "u": 257.75,
    "u_units": "K",
    "molemass": 0.282553,
    "molemass_units": "kg/mol",
    "name": "N-EICOSANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "75-28-5",
    "aliases": [
      "ISOBUTANE",
      "2-METHYLPROPANE"
    ],
    "m": 2.2616,
    "sigma": 3.7574,
    "sigma_units": "1/Angstrom",
    "u": 216.53,
    "u_units": "K",
    "molemass": 0.058123,
    "molemass_units": "kg/mol",
    "name": "ISOBUTANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "78-78-4",
    "aliases": [
      "ISOPENTANE",
      "2-METHYLBUTANE"
    ],
    "m": 2.5620,
    "sigma": 3.8296,
    "sigma_units": "1/Angstrom",
    "u": 230.75,
    "u_units": "K",
    "molemass": 0.07215,
    "molemass_units": "kg/mol",
    "name": "ISOPENTANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "463-82-1",
    "aliases": [
      "NEOPENTANE",
      "2,2-DIMETHYLPROPANE"
    ],
    "m": 2.3543,
    "sigma": 3.9550,
    "sigma_units": "1/Angstrom",
    "u": 225.69,
    "u_units": "K",
    "molemass": 0.07215,
    "molemass_units": "kg/mol",
    "name": "NEOPENTANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "107-83-5",
    "aliases": [
      "2-METHYLPENTANE",
      "ISOHEXANE"
    ],
    "m": 2.9317,
    "sigma": 3.8535,
    "sigma_units": "1/Angstrom",
    "u": 235.58,
    "u_units": "K",
    "molemass": 0.086177,
    "molemass_units": "kg/mol",
    "name": "2-METHYLPENTANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "75-83-2",
    "aliases": [
      "2,2-DIMETHYLBUTANE",
      "NEOHEXANE"
    ],
    "m": 2.6008,
    "sigma": 4.0042,
    "sigma_units": "1/Angstrom",
    "u": 243.51,
    "u_units": "K",
    "molemass": 0.086177,
    "molemass_units": "kg/mol",
    "name": "2,2-DIMETHYLBUTANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "79-29-8",
    "aliases": [
      "2,3-DIMETHYLBUTANE",
      "DIISOPROPYL"
    ],
    "m": 2.6853,
    "sigma": 3.9545,
    "sigma_units": "1/Angstrom",
    "u": 246.07,
    "u_units": "K",
    "molemass": 0.086177,
    "molemass_units": "kg/mol",
    "name": "2,3-DIMETHYLBUTANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "96-14-0",
    "aliases": [
      "3-METHYLPENTANE"
    ],
    "m": 2.8852,
    "sigma": 3.8605,
    "sigma_units": "1/Angstrom",
    "u": 240.48,
    "u_units": "K",
    "molemass": 0.086177,
    "molemass_units": "kg/mol",
    "name": "3-METHYLPENTANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "591-76-4",
    "aliases": [
      "2-METHYLHEXANE"
    ],
    "m": 3.3478,
    "sigma": 3.8612,
    "sigma_units": "1/Angstrom",
    "u": 237.42,
    "u_units": "K",
    "molemass": 0.100204,
    "molemass_units": "kg/mol",
    "name": "2-METHYLHEXANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "287-92-3",
    "aliases": [
      "CYCLOPENTANE"
    ],
    "m": 2.3655,
    "sigma": 3.7114,
    "sigma_units": "1/Angstrom",
    "u": 265.83,
    "u_units": "K",
    "molemass": 0.07013,
    "molemass_units": "kg/mol",
    "name": "CYCLOPENTANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "110-82-7",
    "aliases": [
      "CYCLOHEXANE"
    ],
    "m": 2.5303,
    "sigma": 3.8499,
    "sigma_units": "1/Angstrom",
    "u": 278.11,
    "u_units": "K",
    "molemass": 0.084147,
    "molemass_units": "kg/mol",
    "name": "CYCLOHEXANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "96-37-7",
    "aliases": [
      "METHYLCYCLOPENTANE"
    ],
    "m": 2.6130,
    "sigma": 3.8253,
    "sigma_units": "1/Angstrom",
    "u": 265.12,
    "u_units": "K",
    "molemass": 0.084156,
    "molemass_units": "kg/mol",
    "name": "METHYLCYCLOPENTANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "108-87-2",
    "aliases": [
      "METHYLCYCLOHEXANE"
    ],
    "m": 2.6637,
    "sigma": 3.9993,
    "sigma_units": "1/Angstrom",
    "u": 282.33,
    "u_units": "K",
    "molemass": 0.098182,
    "molemass_units": "kg/mol",
    "name": "METHYLCYCLOHEXANE",
    "BibTeX": "Gross-2001"
  },
  {
    "CAS": "1640-89-7",
    "aliases": [
      "ETHYLCYCLOPENTANE"
    ],
